### ISSUE TITLE
Multiple compatibility issues with pymadcad 1.0+ and uimadcad

### ISSUE THREAD

**Issue by dionarley** [jimy-byerley/pymadcad#145]
### Environment
- Arch Linux
- pymadcad 0.19.1, 0.20.1, 1.0.1
- Python 3.14

### Description
Calling `brick()` without parameters generates NaN coordinates:

```python
from madcad import *
b = brick()
print(b.points)  # [dvec3(-nan, -nan, -nan), ...]
```

### Root Cause
The default `Box` uses `width=vec3(-inf)`. Math: `inf - inf = nan`

### Workaround
Use explicit parameters:
```python
b = brick(center=vec3(0,0,0), width=vec3(1,1,1))
```

---

### Description
uimadcad 0.8.0 requires `pymadcad < 1.0`:

```
ImportError: cannot import name 'ivec4' from 'madcad.mathutils'
```

### Workaround
```bash
pip install "pymadcad==0.19.1"
```

---

### Environment
- Hyprland (Wayland)
- Mesa/Intel GPU

### Description
```
_moderngl.Error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES
```

### Workaround
```bash
export LIBGL_ALWAYS_SOFTWARE=1
```

Also requires fixing desktop file Exec:
```ini
Exec=bash -c "export LIBGL_ALWAYS_SOFTWARE=1; python -m uimadcad"
```

---

## Suggested Fixes
1. Fix brick() default parameters to use finite values (e.g., width=1 instead of -inf)
2. Ensure uimadcad works with pymadcad 1.0+ or document compatibility matrix
3. Add fallback for systems without GLSL 4.30 support

---
Reported on Arch Linux + Hyprland with Python 3.14

**Comment by jimy-byerley** [comment]
Hello, sorry for the delay

- bug 1:  that's on purose. a box defaulting to 0 would have a location while i want to to be neutral in min/max so place at inf
- bug 2:  that seems to be regression of #142, i'm on it
- bug 3:  interesting, i would have expected that it automatically fallbacks
